# Generated by Django 4.2 on 2023-10-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_id_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_category', models.CharField(max_length=50)),
                ('claimed_amount', models.IntegerField()),
                ('comments', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
            ],
        ),
    ]
