# Generated by Django 4.2 on 2023-10-08 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='forkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
