# Generated by Django 4.2 on 2023-10-08 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_expense_forkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='advanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_category', models.CharField(max_length=50)),
                ('claimed_amount', models.IntegerField()),
                ('comments', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('forkey', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
