# Generated by Django 4.2 on 2023-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_advanceexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('truck_no', models.IntegerField()),
            ],
        ),
    ]
