# Generated by Django 4.2 on 2023-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=25)),
                ('arrival', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('truck_type', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=100)),
            ],
        ),
    ]
