# Generated by Django 4.2 on 2023-10-14 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_leads_forkey_loads_forkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.IntegerField()),
                ('truck_driver_name', models.CharField(max_length=50)),
                ('truck_type', models.CharField(max_length=60)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField()),
                ('Aadhaar', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('PAN', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('RC', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('forkey', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
